- name: Join VM
  collections:
    - community.vmware
  hosts: all
  tasks:
    - name: Join VM to domain
      ansible.windows.win_domain_membership:
        dns_domain_name: "{{ domain_name }}"
        domain_admin_user: "{{ domain_admin_user }}"
        domain_admin_password: "{{ domain_admin_password }}"
        state: domain
      register: domain_join
      retries: 3
      delay: 10
      until: domain_join is success

    - name: Reboot VM after domain join
      ansible.windows.win_reboot:
      when: domain_join is changed


    - name: Verify domain membership
      ansible.windows.win_shell: |
        Get-WmiObject -Class Win32_ComputerSystem | Select-Object -ExpandProperty Domain
      register: domain_check

    - name: Display domain membership
      ansible.builtin.debug:
        msg: "VM is joined to domain: {{ domain_check.stdout_lines }}"
