- name: ad VM
  hosts: all
  become: yes
  tasks:  
    - name: Instalar Pacotes para Integracao com AD.
      dnf:
          name:
            - authconfig
            - realmd
            - sssd
            - oddjob
            - oddjob-mkhomedir
            - adcli
            - samba-common
            - samba-common-tools
            - krb5-workstation
            - openldap-clients
            - chrony
          state: present
  
    - name: Copiar kerberos.
      copy:
        src: "krb5.conf"
        dest: "/etc/"
        backup: yes
  
    - name: Copiar samba.
      copy:
        src: "smb.conf"
        dest: "/etc/samba/"
        backup: yes
  
    - name: Copiar chrony.
      copy:
        src: "chrony-realm.conf"
        dest: "/etc/chrony.conf"
        backup: yes
  

  
    - name: Copy sssd.
      copy:
        src: "sssd.conf"
        dest: "/etc/sssd/sssd.conf"
        owner: root
        group: root
        mode: '0600'
        backup: yes
        
    - name: UnJoin the Server
      shell: "realm leave; realm leave; realm leave; realm leave"
      ignore_errors: true
  
    - name: Adicionar ao Dominio usando realm.
      shell: echo '{{JOINPWD}}' | realm join SCL.CORP -U {{JOINACCT}}
      ignore_errors: true
  
    - name: Enable sssd with NSS and PAM.
      shell: /sbin/authconfig --enablesssd --enablesssdauth --enablelocauthorize --enablemkhomedir --update
      ignore_errors: true

    - name: Restart service sssd.
      ansible.builtin.service:
        name: sssd
        state: restarted
        enabled: yes

    - name: Restart service chronyd.
      ansible.builtin.service:
        name: chronyd
        state: restarted
        enabled: yes
