- name: Apply SCCM
  collections:
    - community.vmware
  hosts: all
  tasks:

    - name:  Copy SCCM artifacts
      ansible.windows.win_powershell:
         script: |
          net use Z: {{ fileserver_path }} /user:{{ domain_admin_user }} {{ domain_admin_password }}
          robocopy Z:\. C:\temp\ /e
          net use Z: /delete

    - name: Execute ps1
      ansible.windows.win_shell: >
        powershell.exe -ExecutionPolicy Bypass -File C:\temp\InstallMetricbeat_v2.ps1
