- name: Apply Windows Server 2022 Security Baseline
  collections:
    - community.vmware
  hosts: all
  tasks:

    - name:  Execute MMA
      ansible.windows.win_powershell:
         script: |
          net use Z: {{ fileserver_path }} /user:{{ domain_admin_user }} {{ domain_admin_password }}
          copy Z:\MMASetup-AMD64-10.20.18076.0.exe C:\temp\
          $workspaceIdSentinel = {{ workspaceIdSentinel }}
          $workspaceKey = {{ workspaceKey }}
          $mma = New-Object -ComObject 'AgentConfigManager.MgmtSvcCfg'
          $mma.AddCloudWorkspace($workspaceIdSentinel, $workspaceKey)
          $mma.ReloadConfiguration()
          net use Z: /delete


  
    - name: Copy baseline script
      ansible.windows.win_copy:
        src: files/Baseline-LocalInstall.ps1
        dest: C:\\Temp\\Baseline-LocalInstall.ps1
    - name: Execute security baseline
      ansible.windows.win_shell: >
        powershell.exe -ExecutionPolicy Bypass -File "C:\\Temp\\Baseline-LocalInstall.ps1" -WSNonDomainJoined
      args:
        chdir: C:\\Temp
