- name: Apply ELK
  collections:
    - community.vmware
  hosts: all
  tasks:

    - name:  Copy ELK artifacts
      ansible.windows.win_powershell:
         script: |
          net use Z: {{ fileserver_path }} /user:{{ domain_admin_user }} {{ domain_admin_password }}
          robocopy Z:\. C:\temp\ /e
          net use Z: /delete

    - name: Run my batch file (using win_command - less common for .bat)
      ansible.windows.win_command: C:\\path\\to\\your\\script.bat
      args:
        chdir: C:\\path\\to\\the\\directory\\where\\you\\want\\to\\run\\the\\script
