- name: deploy qualys agent
  collections:
    - ansible.windows
  hosts: all
  tasks:
    - name: Set the execution policy to Unrestricted first
      win_shell: Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Scope LocalMachine -Force
      tags: always
