- name: Remove Windows user and delete profile
  hosts: all
  gather_facts: no
  become: false
  collections:
    - ansible.windows

  vars:
    username: "guest"  # Altere para o nome do usuário a ser removido

  tasks:
    - name: Disable built-in user account (e.g., Guest)
      ansible.windows.win_user:
        name: Guest
        account_disabled: yes
        state: present

