- name: Deploy Machine
  collections:
    - community.vmware
  hosts: all
  tasks:
    - name: Check if script already ran
      win_reg_stat:
        path: HKLM:\Software\CustomScripts
        name: BaselineScriptRun
      register: baseline_check
      
    - name: Set PowerShell execution policy to Unrestricted
      win_shell: |
        Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Force -Scope LocalMachine
      when: not baseline_check.exists
