- name: Checking Machine
  hosts: all
  tasks:
    - name: Wait for WinRM to be available
      ansible.windows.win_ping:
      register: winrm_check
      retries: 300
      delay: 100
      until: winrm_check is success
      ignore_errors: true
 
    - name: Debug WinRM check
      ansible.builtin.debug:
        var: winrm_check
      when: winrm_check.failed

    - name: Optional - Display activation status
      win_shell: "cscript.exe C:\\Windows\\System32\\slmgr.vbs /dli"
      register: activation_status
