- name: Instalar pacotes necessários via YUM
  hosts: all
  become: yes
  tasks:      
    - name: Instalar pacotes com yum
      ansible.builtin.yum:
        name:
          - git
          - gcc
          - gcc-c++
          - nodejs
          - gettext
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
          - bzip2
          - python3-pip
          - nano
          - wget
        state: present
        
    - name: Adicionar repositório Docker
      ansible.builtin.command: >
        yum-config-manager --add-repo https://download.docker.com/linux/rhel/docker-ce.repo
      args:
        creates: /etc/yum.repos.d/docker-ce.repo

    - name: Instalar pacotes com yum
      ansible.builtin.yum:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
