- name: deploy qualys agent
  collections:
    - community.general
  hosts: all
  tasks:
    - name: Add an Team connection with static IP configuration
      nmcli:
        conn_name: my-team1
        ifname: my-team1
        type: team
        ip4: 192.0.2.100/24
        gw4: 192.0.2.1
        state: present
        autoconnect: true
