- name: Deploy MMA agent on Windows
  hosts: all
  gather_facts: no
  vars:
    workspace_id: "{{ mma_workspace_id }}"
    workspace_key: "{{ mma_workspace_key }}"
    mma_download_url: "https://go.microsoft.com/fwlink/?LinkID=828603"
    mma_installer_path: "C:\\Temp\\MMASetup-AMD64.exe"
    mma_extract_path: "C:\\Temp\\MMAExtract"

  tasks:
    - name: Garantir diretório C:\Temp
      ansible.windows.win_file:
        path: "C:\\Temp"
        state: directory

    - name: Baixar o instalador do MMA
      ansible.windows.win_get_url:
        url: "{{ mma_download_url }}"
        dest: "{{ mma_installer_path }}"
        validate_certs: no

    - name: Extrair instalador do MMA
      ansible.windows.win_shell: >
        "{{ mma_installer_path }}" /Q /C /T:{{ mma_extract_path }}
      args:
        chdir: "C:\\Temp"

    - name: Instalar Microsoft Monitoring Agent
      ansible.windows.win_shell: >
        Start-Process -FilePath "{{ mma_extract_path }}\\Setup.exe" `
        -ArgumentList "/qn ADD_OPINSIGHTS_WORKSPACE=1 OPINSIGHTS_WORKSPACE_ID={{ workspace_id }} OPINSIGHTS_WORKSPACE_KEY={{ workspace_key }} AcceptEndUserLicenseAgreement=1" `
        -Wait
      args:
        executable: powershell.exe
