- name: Deploy MMA agent on Windows
  collections:
    - ansible.windows
  hosts: all
  vars:
    workspace_id: "{{ mma_workspace_id }}"
    workspace_key: "{{ mma_workspace_key }}"
    mma_download_url: "https://go.microsoft.com/fwlink/?LinkID=828603"
    mma_installer: "C:\\Temp\\MMASetup-AMD64.exe"
    install_args: >
      /Q
      ADD_OPINSIGHTS_WORKSPACE=1
      OPINSIGHTS_WORKSPACE_ID={{ workspace_id }}
      OPINSIGHTS_WORKSPACE_KEY={{ workspace_key }}
      AcceptEndUserLicenseAgreement=1
  tasks:
    - name: Download MMA agent
      ansible.windows.win_get_url:
        url: "{{ mma_download_url }}"
        dest: "{{ mma_installer }}"
        validate_certs: no

    - name: Install Microsoft Monitoring Agent silently
      ansible.windows.win_shell: >
        Start-Process -FilePath "{{ mma_installer }}" -ArgumentList '{{ install_args }}' -Wait
