- name: deploy MMA agent
  collections:
    - ansible.windows
  hosts: all
  tasks:
    - name: Copy installer from network share
      ansible.windows.win_command: >
        cmd.exe /c copy "{{ fileserver_path }}" "{{ local_path }}"
      args:
        creates: "{{ local_path }}"

    - name: Install MMA silently
      ansible.windows.win_command: >
        "{{ local_path }}" /quiet
#    - name:  Execute MMA
#      ansible.windows.win_powershell:
#         script: |
#          net use Z: {{ fileserver_path }}
#          copy Z:\MMASetup-AMD64-10.20.18076.0.exe C:\temp\
#          $workspaceIdSentinel = {{ mma_workspace_key }}
 #         $workspaceKey = {{ mma_workspace_id }}
#          $mma = New-Object -ComObject 'AgentConfigManager.MgmtSvcCfg'
#          $mma.AddCloudWorkspace($workspaceIdSentinel, $workspaceKey)
#          $mma.ReloadConfiguration()
#          net use Z: /delete
