- name: deploy MMA agent
  collections:
    - ansible.windows
  hosts: all
  tasks:


- name: Apply SCCM
  collections:
    - community.vmware
  hosts: all
  tasks:

    - name:  Copy MMA artifacts
      ansible.windows.win_powershell:
         script: |
          net use Z: {{ fileserver_path }} /user:{{ domain_admin_user }} {{ domain_admin_password }}
          robocopy Z:\. C:\temp\ /e
          net use Z: /delete

    - name:  Execute MMA
      ansible.windows.win_powershell:
         script: |
          $workspaceIdSentinel = {{ mma_workspace_key }}
          $workspaceKey = {{ mma_workspace_id }}
          $mma = New-Object -ComObject 'AgentConfigManager.MgmtSvcCfg'
          $mma.AddCloudWorkspace($workspaceIdSentinel, $workspaceKey)
          $mma.ReloadConfiguration()
