- name: Deploy MMA agent on Windows
  collections:
    - ansible.windows
  hosts: all
  vars:
    workspace_id: "{{ mma_workspace_id }}"
    workspace_key: "{{ mma_workspace_key }}"
    mma_download_url: "https://go.microsoft.com/fwlink/?LinkID=828603"
    mma_installer: "C:\\Temp\\MMASetup-AMD64.exe"
    install_args: >
      /Q
      ADD_OPINSIGHTS_WORKSPACE=1
      OPINSIGHTS_WORKSPACE_ID={{ workspace_id }}
      OPINSIGHTS_WORKSPACE_KEY={{ workspace_key }}
      AcceptEndUserLicenseAgreement=1
  tasks:
#    - name: Baixar o instalador do MMA
#      ansible.windows.win_get_url:
#        url: "https://go.microsoft.com/fwlink/?LinkID=828603"
#        dest: "C:\\Temp\\MMASetup-AMD64.exe"
#        validate_certs: no
    
    - name: Extrair e instalar Microsoft Monitoring Agent
      ansible.windows.win_shell: |
        C:\temp\MMASetup-AMD64.exe /Q /C /T:C:\temp\MMAExtract
        Start-Process -FilePath "C:\temp\MMAExtract\Setup.exe" `
          -ArgumentList "/qn ADD_OPINSIGHTS_WORKSPACE=1 OPINSIGHTS_WORKSPACE_ID={{ workspace_id }} OPINSIGHTS_WORKSPACE_KEY={{ workspace_key }} AcceptEndUserLicenseAgreement=1" `
          -Wait

