- name: deploy MMA agent
  collections:
    - ansible.windows
  hosts: all
  tasks:


- name: Apply SCCM
  collections:
    - community.vmware
  hosts: all
  tasks:

    - name:  Copy MMA artifacts
      ansible.windows.win_powershell:
         script: |
          net use Z: {{ fileserver_path }} /user:{{ domain_admin_user }} {{ domain_admin_password }}
          robocopy Z:\. C:\temp\ /e
          net use Z: /delete

#    - name: Copy installer from network share
#      ansible.windows.win_command: >
#        cmd.exe /c copy "{{ fileserver_path }}" "{{ local_path }}"
#      args:
#        creates: "{{ local_path }}"

#    - name: Install MMA silently
#      ansible.windows.win_command: >
#       "C:\\temp\\MMASetup-AMD64-10.20.18076.0.exe" /quiet
#    - name:  Execute MMA
#      ansible.windows.win_powershell:
#         script: |
#          net use Z: {{ fileserver_path }}
#          copy Z:\MMASetup-AMD64-10.20.18076.0.exe C:\temp\
#          $workspaceIdSentinel = {{ mma_workspace_key }}
 #         $workspaceKey = {{ mma_workspace_id }}
#          $mma = New-Object -ComObject 'AgentConfigManager.MgmtSvcCfg'
#          $mma.AddCloudWorkspace($workspaceIdSentinel, $workspaceKey)
#          $mma.ReloadConfiguration()
#          net use Z: /delete
