- name: Deploy Machine
  collections:
    - community.vmware
  hosts: all
  tasks:
    - name: Deploy Linux VM from template
      community.vmware.vmware_guest:
        validate_certs: "{{ validate_certs }}"
        name: "{{ vm_name }}"
        template: "{{ template_name }}"
        datacenter: "{{ datacenter_name }}"
        folder: "{{ vm_folder }}"
        cluster: "{{ cluster_name }}"
        datastore: "{{ datastore_name }}"
        hardware:
          memory_mb: 2048
          num_cpus: "{{ var_num_cpus }}"
          scsi: paravirtual
        networks:
          - name: "{{ network_name }}"
            network_name: "{{ network_name }}"
            label: "{{ interface_name }}"
            device_type: vmxnet3
            start_connected: true
            connected: true
            type: static
            ip: "{{ ip_address }}"
            netmask: "{{ var_subnet_mask }}"
            gateway: "{{ var_gateway }}"
            dns_servers: "{{ var_dns }}"
            state: present
        state: poweredon
        wait_for_ip_address: true
      delegate_to: localhost
      register: vm_deploy

    - name: Debug VM deployment result
      ansible.builtin.debug:
        var: vm_deploy
      when: vm_deploy.failed
