- name: Checking Machine
  hosts: all
  tasks:
    - name: Get product id and product key
      community.windows.win_product_facts:
      
    - name: Display Windows license status
      debug:
        var: ansible_os_license_status

    - name: Print OS details
      debug:
        msg: "OS: {{ ansible_distribution }}"
