- name:  Deploy Linux Server VM in VMWAre
  collections:
    - community.vmware
  hosts: all
  tasks:
  vars:
    validate_certs: false
    network_name: "{{ var_vlan }}"
    ip_address: "{{ var_ip }}"
    subnet_mask: "{{ var_mask }}"
    gateway: "{{ var_gw }}"
    dns_servers:
      - "{{ var_dns1 }}"
      - "{{ var_dns2 }}"
        #    domain_name: "{{ var_dominio }}"
    hostname: "{{ var_nome_vm }}"
    domain_admin_user: n1-dtc-crpa@scl.corp
    domain_admin_password: "{{ domain_n1_password }}"
    ansible_ssh_user: administrator
    ansible_ssh_pass: "{{ local_password }}"

  tasks:
    - name: Deploy Linux VM from template
      community.vmware.vmware_guest:
        validate_certs: "{{ validate_certs }}"
        name: "{{ vm_name }}"
        template: "{{ template_name }}"
        datacenter: "{{ datacenter_name }}"
        folder: "{{ vm_folder }}"
        cluster: "{{ cluster_name }}"
        datastore: "{{ datastore_name }}"
        hardware:
          memory_mb: "{{ var_mem }}"
          num_cpus: "{{ var_cpu }}"
          scsi: paravirtual
        networks:
          - name: "{{ network_name }}"
            network_name: "{{ network_name }}"
            label: "{{ interface_name }}"
            device_type: vmxnet3
            start_connected: true
            connected: true
            type: static
            ip: "{{ ip_address }}"
            netmask: "{{ subnet_mask }}"
            gateway: "{{ gateway }}"
            dns_servers:
              - "{{ var_dns1 }}"
              - "{{ var_dns2 }}"
            state: present
        customization:
          hostname: "{{ hostname }}"
        wait_for_customization: true
        state: poweredon
        wait_for_ip_address: true
      delegate_to: localhost
      register: vm_deploy

    - name: Debug VM deployment result
      ansible.builtin.debug:
        var: vm_deploy
      when: vm_deploy.failed

    - name: Wait for SSH to be available
      ansible.builtin.wait_for_connection:
        timeout: 300
      register: wait_result
      delegate_facts: true
      delegate_to: localhost

    - name: Debug wait result
      debug:
        msg: "{{ wait_result }}"
