- name: deploy qualys agent
  collections:
    - ansible.windows
  hosts: all
  tasks:
    - name: Copiar arquivo para o destino
      ansible.builtin.copy:
       src: "QualysCloudAgent.exe"
       dest: C:\temp\


    - name: Install Qualys agent with registration key, activation ID, and web service URI
      ansible.windows.win_package:
        path: C:\temp\QualysCloudAgent.exe"
        arguments: "/qn /CustomerId={ {{ CustomerId }} } /ActivationId={ {{ ActivationId }} } /WEB_SERVICE_URI=https://qagpublic.qg4.apps.qualys.com/CloudAgent/" # Updated args with explicit curly braces
        state: present
