- name: deploy qualys agent
  collections:
    - ansible.windows
  hosts: all
  tasks:
    - name: Copiar arquivo para o destino
      ansible.builtin.copy:
       src: "QualysCloudAgent.exe"
       dest: C:\temp\

    - name: Install Qualys Cloud Agent
      win_shell: |
        & "C:\Temp\QualysCloudAgent.exe" CustomerId={{ CustomerId }} ActivationId={{ ActivationId }} WebServiceUri={{ WebServiceUri }}
      args:
        creates: "C:\Program Files\Qualys\QualysAgent\QualysAgent.exe" # Prevents re-installation if already present
