- name: deploy qualys agent
  collections:
    - ansible.windows
  hosts: all
  tasks:
    - name: Copiar arquivo para o destino
      ansible.builtin.copy:
       src: "QualysCloudAgent.exe"
       dest: C:\temp\

    - name: Install Qualys Agent
      ansible.windows.win_package:
        path: 'c:\temp\QualysCloudAgent.exe'
        state: present
        arguments:
          - CustomerId={{ "{CustomerId}" }}
          - ActivationId={{ "{ActivationId}" }}
          - WebServiceUri=https://qagpublic.qg4.apps.qualys.com/CloudAgent/
