- name: deploy qualys agent
  collections:
    - ansible.windows
  hosts: all
  tasks:
    - name: Copiar arquivo para o destino
      ansible.builtin.copy:
       src: "QualysCloudAgent.exe"
       dest: C:\temp\

    - name: Install Qualys Agent on the machine
      win_package:
        path: C:\Temp\QualysCloudAgent.exe
        productid: auto
        state: present
        arguments:
        - CustomerId={'CustomerId'}
        - ActivationId={'ActivationId'}
        - WebServiceUri={'WebServiceUri'}
        - /install
        - /passive
        - /norestart
