- name: Register
  hosts: all
  become: yes
  collections:
    - community.general
  tasks:
    - name: Registrar no Red Hat Subscription Manager (modo user/pass)
      community.general.redhat_subscription:
        state: present
        username: "{{ rhsm_username }}"
        password: "{{ rhsm_password }}"
        auto_attach: true
