- name: set timezone
  collections:
    - ansible.windows
  hosts: all
  tasks:
    - name: Configure Windows region
      community.windows.win_region:
        format: "pt-BR" # Example format
        copy_settings: true
