- name: set timezone
  collections:
    - community.windows
  hosts: all
  tasks:
    - name: Configure Windows region
      community.windows.win_region:
        location: 32              # Código da região: Brazil
        format: "pt-BR"           # Formato de exibição regional
        copy_settings: true       # Copiar configurações para tela de login e novos usuários
