- name: set timezone
  collections:
    - community.windows
  hosts: all
  tasks:
    - name: Configure Windows region
      community.windows.win_region:
        location: 32
        format: "pt-BR" # Example format
        copy_settings: true
