- name: set timezone
  collections:
    - ansible.windows
  hosts: all
  tasks:
    - name: Configure Windows region
      ansible.windows.win_region:
        location: "Brazil" # Example location
        format: "pt-BR" # Example format
        copy_settings: true
