- name: deploy sss
  hosts: all
  tasks:
    - name: Install required packages
      package:
        name:
          - realmd
          - sssd
          - oddjob
          - oddjob-mkhomedir
          - adcli
          - samba-common
          - samba-common-tools
          - krb5-workstation
          - sssd-tools
        state: present

    - name: Ensure oddjobd is running
      service:
        name: oddjobd
        state: started
        enabled: yes

    - name: Join the machine to AD domain
      expect:
        command: realm join {{ domain_name }} -U {{ domain_user }}
        responses:
          Password for *: "{{ domain_password }}"
      register: join_result
      failed_when: "'failed' in join_result.stderr.lower()"

    - name: Configure SSSD to create home directories on login
      lineinfile:
        path: /etc/sssd/sssd.conf
        regexp: '^fallback_homedir'
        line: 'fallback_homedir = /home/%u'
        insertafter: '[domain/{{ domain_name | lower }}]'
        create: yes
        mode: '0600'

    - name: Restart SSSD
      service:
        name: sssd
        state: restarted
