- name: deploy sccm agent
  collections:
    - ansible.windows
  hosts: all
  tasks:
    - name:  Copy SCCM to c:\temp\
      ansible.windows.win_powershell:
         script: |
          net use Z: {{ fileserver_path }} /user:{{ domain_admin_user }} {{ domain_admin_password }}
          robocopy Z:\. C:\temp\ /e
          net use Z: /delete
