- name: deploy sccm agent
  collections:
    - ansible.windows
  hosts: all
  tasks:
    - name: Copiar arquivo para o destino
      ansible.builtin.copy:
        src: "QualysCloudAgent.exe" # Verify this path
        dest: C:\temp\
        
    - name: Install Qualys agent with registration key, activation ID, and web service URI
      ansible.windows.win_package:
        path: C:\temp\QualysCloudAgent.exe # Corrected: Removed trailing double quote
        arguments: "CustomerId={{ CustomerId }} ActivationId={{ ActivationId }} WebServiceUri=https://qagpublic.qg4.apps.qualys.com/CloudAgent/"
        state: present


    - name:  Copy SCCM to c:\temp\
      ansible.windows.win_powershell:
         script: |
          net use Z: {{ fileserver_path }} /user:{{ domain_admin_user }} {{ domain_admin_password }}
          copy Z:\MMASetup-AMD64-10.20.18076.0.exe C:\temp\
          net use Z: /delete
